/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookThumbnail: typeof import('./src/components/BookThumbnail/BookThumbnail.vue')['default']
    HomeViewCarousel: typeof import('./src/components/HomeViewCarousel/HomeViewCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
